version: '3'
volumes:
  mongo-data:

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://mongo:27017/hospital

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
